### ISSUE TITLE
Plugin is not loading

### ISSUE THREAD

**Issue by chamira** [CocoaPods/cocoapods-appledoc#8]
Error loading the plugin `cocoapods-appledoc-0.1.0`.

Gem::ConflictError - Unable to activate cocoapods-appledoc-0.1.0, because cocoapods-1.0.1 conflicts with cocoapods (~> 0.34)
/Users/someuser/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2112:in `raise_if_conflicts'
/Users/someuser/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1280:in`activate'
/Users/someuser/.rvm/gems/ruby-2.2.4/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:94:in `safe_activate_and_require'
/Users/someuser/.rvm/gems/ruby-2.2.4/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:31:in`block in load_plugins'
/Users/someuser/.rvm/gems/ruby-2.2.4/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:30:in `map'
/Users/someuser/.rvm/gems/ruby-2.2.4/gems/claide-1.0.0/lib/claide/command/plugin_manager.rb:30:in`load_plugins'
/Users/someuser/.rvm/gems/ruby-2.2.4/gems/claide-1.0.0/lib/claide/command.rb:326:in `block in run'
/Users/someuser/.rvm/gems/ruby-2.2.4/gems/claide-1.0.0/lib/claide/command.rb:325:in`each'
/Users/someuser/.rvm/gems/ruby-2.2.4/gems/claide-1.0.0/lib/claide/command.rb:325:in `run'
/Users/someuser/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in`run'
/Users/someuser/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/Users/someuser/.rvm/rubies/ruby-2.2.4/bin/pod:23:in`load'
/Users/someuser/.rvm/rubies/ruby-2.2.4/bin/pod:23:in `<main>'
/Users/someuser/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in`eval'
/Users/someuser/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'

**Comment by jcesarmobile** [comment]
Same problem
I don't think this is maintained
